### ISSUE TITLE
Not supported on Gnome 42

### ISSUE THREAD

**Issue by eloyekunle** [grantmcwilliams/Gnome_Hide_Clock#1]
This extension is no longer compatible with the latest GNOME versions. I am getting this error with v42.0 on Ubuntu 22.04.

![image](https://user-images.githubusercontent.com/11166933/164582768-99f337f5-92cd-473a-86ab-fe8467ada57a.png)

**Comment by grantmcwilliams** [comment]
I'm aware, thanks. There's another extension called hide date that works.
They're basically doing the same thing but that one is updated for 42.

**Comment by eloyekunle** [comment]
Can you share a link, please? This is what I can find.

![image](https://user-images.githubusercontent.com/11166933/164778958-aeaee92f-bd9f-4f13-9f3a-b40febb1e83a.png)

**Comment by grantmcwilliams** [comment]
That's the one, send them a message and they just need to change the
metadata in the extension. I'm fairly positive I had it working on Gnome
42.

**Comment by eloyekunle** [comment]
I downloaded it locally and updated the metadata. Thanks!

**Comment by grantmcwilliams** [comment]
No problem. I'm on vacation now but when I return I'll update my extension.
There's no reason to have hide clock and hide date as they do the same
thing but we have documentation at work that calls mine so I'll try to keep
it updated.
