### ISSUE TITLE
The extension is fantastic, but I can't see the date.

### ISSUE THREAD

**Issue by Sharath44665** [grantmcwilliams/Gnome_Hide_Clock#2]
### When enabled, the following are the issues:
1. unable to see the date
2. not being able to see the notification area
### when disabled:
Back to normal

**Comment by Sharath44665** [comment]
![issue1](https://user-images.githubusercontent.com/66732823/201974048-f3075d1c-535d-4718-a4df-41a1eb5110ea.png)

**Comment by grantmcwilliams** [comment]
Glad you like the plugin. As for the issue the Time and Date are actually the same object. If I make it disappear then the other does as well.  Gnome_tweaks allows you to disable portions of it (not the time alone) but I haven't looked into how it's done. I created this because I create video training courses and editing video gets weird if the clock is visible so I needed the clock gone.

**Comment by Sharath44665** [comment]
Can you please share with me where you get the information on these extension creations? I looked into this [https://gjs.guide/extensions/](https://gjs.guide/extensions/) and I followed few tutorials from there and checked a few source codes in [https://gitlab.gnome.org/GNOME/gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell) but i am unable to modify  your  code `dateMenu.container` or `Panel.statusArea.dateMenu;`

Please share the resources with me if at all possible.

> further requesting that to close this issue.

**Comment by grantmcwilliams** [comment]
You can git clone my repository and change what you want. When you get it to work the way you want you can always do a pull request. I'm not against my extension having more functionality, I don't change it because it works for me.

**Comment by Sharath44665** [comment]
## Thanks for your response.

I found another alternative [extension](https://extensions.gnome.org/extension/1462/panel-date-format/) so that I could tweak it easily in the way I wanted. 
### Anyway, thanks again.
